### PR TITLE
Updates documentation header

### PR DESCRIPTION
**Pull request by glauco**
**Before:**

screen shot 2016-07-28 at 10 50 15 am

**After:**

screen shot 2016-07-28 at 10 51 21 am

This commit includes:
- A new header logo
- Updates the first documentation header, explaining what this page
actually is
- Updates CSS to better position logo on header

### CODE REVIEW

**Comment by waldemarnt** [comment]
can you update the PR including an screenshot?

**Comment by jeffhsta** [comment]
:+1:

**Comment by waldemarnt** [comment]
👍

**Comment by lucaslago** [comment]
👍

**Comment by carolinaborim** [comment]
👍

**Comment by andressa** [comment]
👍

**Pull request merged**
