### PR TITLE
Requires custom schema tab

### PR DESCRIPTION
**Pull request by waldemarnt**
Before:
the schema tabs is no changing the content

screen shot 2016-08-18 at 5 01 23 pm

After:
we can change the content between tabs
screen shot 2016-08-18 at 5 01 39 pm

### CODE REVIEW

**Comment by lucaslago** [comment]
@waldemarnt in the "after" image, is that highlighted part expected behaviour? I believe it was supposed to be a JSON schema, right?

**Comment by waldemarnt** [comment]
@lucaslago the json will be placed there when we run `rake build`, this is only a pattern to let the build script know where the schema should be placed, make sense?

**Comment by lucaslago** [comment]
:+1:

**Comment by jeffhsta** [comment]
:+1:

**Pull request merged**
