### PR TITLE
Removing useless text on the first page

### PR DESCRIPTION
**Pull request by glauco**
For demo purposes we included a few lines of documentation around
Telemetry API brands endpoint.

It is completely useless right now.

Given we want to get qualitative feedback around the documentation, this
commit removes it.

### CODE REVIEW

**Comment by andressa** [comment]
👍

**Comment by waldemarnt** [comment]
👍

**Comment by jeffhsta** [comment]
:+1:

**Comment by bltavares** [comment]
Given that we are removing the placeholder for content, should we already expand the information on the introduction section?

**Comment by glauco** [comment]
@bltavares Yes! We should!

I will do that on a separated pull request.

Would that be OK?!

**Comment by bltavares** [comment]
@glauco I think that is ok. I was just worried that we would remove a lot of content on the page and take a while to add things again.

**Pull request merged**
